[actor]
type = static
interactable = event
size = 16, 16

[state:closed]
sprite = basicset@36
collision = true

[state:opened]
sprite = basicset@35
collision = true


# Per instance properties, defaults
[instance]
state = closed
