[actor]
type = static
interactable = script
script = lua_door

[state:closed]
sprite = basicset@48
collision = true

[state:opened]
sprite = basicset@50
collision = false

# Per instance properties, defaults
[instance]
state = closed
