[core]
language = en

[platform]
width = 640
height = 480
scale = 2

[platform:DOS]
mode = 12

# Hash NAME -> FILE overwrites
[resourcemap]
defaultpalette = pal.ini
helloworld = wh1.ini
samsettileset = tileset.png
wh1tileset = basicset.ini
CHEST_CLOSED = chcl.gif
CHEST_OPENED = chop.gif
