[core]
language = en

[platform]
width = 640
height = 480
scale = 2

[platform:DOS]
mode = 12

# Hash NAME -> FILE overwrites
[resourcemap]
defaultpalette = pal.ini
helloworld = wh1.ini
samsettileset = tileset.png
wh1tileset = basicset.ini
actor_chest_level1 = CHLV1.ini
actor_door = door.ini
